apiVersion: v1
kind: LimitRange
metadata:
  name: dineops-default-limits
  namespace: dineops
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "2"
        memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dineops-resource-quota
  namespace: dineops
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "4"
    limits.memory: 5Gi
    persistentvolumeclaims: "5"
    requests.storage: 10Gi
    pods: "20"
