ALTER TABLE restaurants
    ADD COLUMN IF NOT EXISTS notify_customer_email BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notify_customer_sms BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS customer_email VARCHAR(255);
