spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dineops
    username: dineops
    password: dineops123
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379